name: weekly

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 1" # Run every Monday at midnight UTC

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo content
              uses: actions/checkout@v2 # Checkout the repository content to github runner.

            - name: Set up python
              uses: actions/setup-python@v1 # Set up the python 3.10 environment
              with:
                  python-version: "3.12"

            - name: Install dependencies with pipenv
              run: |
                  pip install pipenv
                  pipenv install --deploy --dev

            - name: Execute python script # Run the main.py script to get the latest data
              run: |
                  make run

            - name: Post script cleanup
              run: |
                  pipenv run isort --diff .
                  pipenv run black --check .
                  pipenv run flake8
                  pipenv run mypy

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "chore: weekly vaults update"
                  file_pattern: "Data.md state.json"
                  commit_user_name: "vaults[bot]"
